---
- name: Clean up temporary files
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /tmp/terraform.zip
    - /tmp/helm.tar.gz
    - /tmp/tfswitch.tar.gz
    - /tmp/terraform-docs.tar.gz

- name: Display completion message
  debug:
    msg: |
      ===============================================
      BOOTSTRAP COMPLETED SUCCESSFULLY!
      ===============================================
      
      Installed Tools:
      - Docker & Docker Compose
      - Kubernetes: kubectl, minikube, kind, Helm
      - Terraform {{ terraform_version }} + tfswitch
      - Ansible {{ ansible_version }}
      - Development tools (git, python, etc.)
      
      Next Steps:
      1. Log out and log back in for group changes to take effect
      2. Start minikube: minikube start --driver=docker --nodes 3
      3. Verify installations:
         - docker --version
         - kubectl version --client
         - terraform version
         - ansible --version
      
      Minikube node labeling:
        kubectl label node minikube type=application
        kubectl label node minikube-m02 type=database  
        kubectl label node minikube-m03 type=dependent_services
      ===============================================