---
- name: Create terraform directory
  file:
    path: /opt/terraform
    state: directory
    mode: '0755'

- name: Download Terraform
  get_url:
    url: "https://releases.hashicorp.com/terraform/{{ terraform_version }}/terraform_{{ terraform_version }}_linux_amd64.zip"
    dest: /tmp/terraform.zip

- name: Extract Terraform
  unarchive:
    src: /tmp/terraform.zip
    dest: /usr/local/bin
    remote_src: yes
    mode: '0755'
    creates: /usr/local/bin/terraform

- name: Install tfswitch (Terraform version manager)
  get_url:
    url: https://github.com/warrensbox/terraform-switcher/releases/download/0.13.1308/terraform-switcher_0.13.1308_linux_amd64.tar.gz
    dest: /tmp/tfswitch.tar.gz

- name: Extract tfswitch
  unarchive:
    src: /tmp/tfswitch.tar.gz
    dest: /usr/local/bin
    remote_src: yes
    extra_opts:
      - --strip-components=1
    creates: /usr/local/bin/tfswitch

- name: Create tfswitch config directory
  file:
    path: "{{ ansible_env.HOME }}/.terraform.versions"
    state: directory
    mode: '0755'

- name: Install terraform-docs
  get_url:
    url: https://github.com/terraform-docs/terraform-docs/releases/download/v0.16.0/terraform-docs-v0.16.0-linux-amd64.tar.gz
    dest: /tmp/terraform-docs.tar.gz

- name: Extract terraform-docs
  unarchive:
    src: /tmp/terraform-docs.tar.gz
    dest: /usr/local/bin
    remote_src: yes
    extra_opts:
      - --strip-components=1
    creates: /usr/local/bin/terraform-docs